### ISSUE TITLE
Instance-awareness broken

### ISSUE THREAD

**Issue by battis** [smtech/canvashack#8]
The changes introduced in [this](https://github.com/smtech/canvashack/commit/c9dc586cff89dca441e638f94ac71b189b727e80) commit are not really safe (the API tends to revert to the setting in `config.xml` rather than the LTI authentication information), as described [here](https://github.com/smtech/canvas-management/issues/12).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/199881049396186/199881087512593)

**Comment by smtech-unito-sync** [comment]
➤ Seth Battis commented:
Testing markdown-here sync through Unito to GitHub.


​

**Comment by battis** [comment]
This needs to fall back to detecting the referrer if there is no LTI data, I guess.

**Comment by battis** [comment]
Hrm. Looks like non-root pages are not getting the script loaded!

**Comment by sapoman88** [comment]
Cleaning up a few things from my script to have naming conventions more consistent… none of the data is in there right now… It will be up within the hour…. Figured youd be teaching an not notice..


Carlos Collazo

**Comment by battis** [comment]
Nope. The problem is definitely deeper (architectural) and needs further probing. Essentially, if we stay at `smtech/reflexive-canvas-lti` version 1.0.5, we can fall back to using the stored Canvas API url in the AppMetadata, but 1.0.6 (intentionally) breaks that fall-back.

But… we are doing an end-run around LTI authentication when we load `canvashack.css.php` and `canvashack.js.php`, so we don't have `$_SESSION[ToolProvider::class]['canvas']['api_domain']` set to provide an API domain for CanvasPest. We can get it from

```PHP
parse_url($_SERVER['HTTP_REFERER'], PHP_URL_HOST)
````

…but I need to do some deeper thinking about the logic of how that works. Plus, even if we use `HTTP_REFERER` to explicitly set 'api_domain', PHP is throwing errors about how `ToolProvider::class` is an unknown index — even as it prints out the contents of that index.

&#128169;

**Comment by battis** [comment]
…and I don't think this is really a breaking bug at this point. It's more of an annoying bug. The way it would manifest itself is by, say, showing lists of assignment templates from the live instance while browsing the test instance, or scrolling through a roster in the Faculty Journal built from the live instance rather than the test instance, or redirecting from the test instance to the live instance, when it should have stayed on the test instance.

That is: people on the live instance are unaffected, but people testing things on the test instance get annoyed and frustrated.

**Comment by battis** [comment]
Consider using `IGNORE_LTI` to treat non-LTI pages as special case. 

This is why you leave your desk.

**Comment by battis** [comment]
[Fixed.](https://github.com/smtech/canvashack/commit/8f6bcec7d08e6fe71ee4b19ae21643eba900b0a5)

**Comment by battis** [comment]
[Really fixed now.](https://github.com/smtech/canvashack/commit/39e1710d4b2a88078c4f9914170b3f980e77f958)
